#!/usr/bin/env node
// check-i18n.ts — i18n integrity gate for Ithmb-Codec-Web.
//
// Verifies:
//  1. Key parity: locales/en.json and locales/zh.json have IDENTICAL key sets.
//  2. No raw user-facing literals: user-facing strings must come from t()/data-i18n,
//     not hardcoded literals in ithmb-decoder/*.ts.
//  3. Placeholder match: every {param} referenced in a value exists in the key's
//     usage (checked via t("key", {param}) call sites).
//
// Exit 0 = all checks pass. Non-zero = failure (for CI / pre-commit).
import { readFileSync, readdirSync } from "node:fs";
import { join } from "node:path";

const ROOT = join(import.meta.dirname, "..");
const DECODER = join(ROOT, "ithmb-decoder");
const LOCALES = join(DECODER, "locales");

let failures = 0;
const fail = (msg: string) => {
  failures++;
  console.error("FAIL:", msg);
};

// ---- 1. Key parity ----
const en = JSON.parse(readFileSync(join(LOCALES, "en.json"), "utf8")) as Record<string, string>;
const zh = JSON.parse(readFileSync(join(LOCALES, "zh.json"), "utf8")) as Record<string, string>;
const enKeys = new Set(Object.keys(en));
const zhKeys = new Set(Object.keys(zh));
for (const k of enKeys) if (!zhKeys.has(k)) fail(`key "${k}" in en.json but NOT in zh.json`);
for (const k of zhKeys) if (!enKeys.has(k)) fail(`key "${k}" in zh.json but NOT in en.json`);
console.log(`[1] key parity: ${enKeys.size} en keys / ${zhKeys.size} zh keys`);

// ---- 2. No raw user-facing literals ----
// Known non-translatable constants (keyboard keys, format names, API constants).
const ALLOWLIST = new Set([
  "Files",
  "ArrowRight",
  "ArrowDown",
  "ArrowLeft",
  "ArrowUp",
  "Escape",
  "JPEG",
  "PNG",
  "BMP",
  "WebP",
  "SHA-256",
  "POST",
  "TITLE",
  "Content-Type",
  "Error",
  "image/jpeg",
  "image/png",
  "image/bmp",
  "image/webp",
]);
const jsFiles = readdirSync(DECODER).filter(
  (f) => f.endsWith(".ts") && !f.includes("ithmb_wasm") && f !== "i18n.ts",
);
for (const f of jsFiles) {
  const rawSrc = readFileSync(join(DECODER, f), "utf8");
  // Strip comments so only real code is scanned (comments may reference
  // strings that are legitimately keyed elsewhere).
  const src = rawSrc.replace(/\/\*[\s\S]*?\*\//g, "").replace(/(^|[^:])\/\/.*$/gm, "$1");
  // User-facing prose: quoted strings starting with a capital, 3+ chars.
  const re = /"([A-Z][A-Za-z][^"]{2,})"/g;
  let m: RegExpExecArray | null;
  while ((m = re.exec(src))) {
    const s = m[1];
    if (ALLOWLIST.has(s)) continue;
    if (/^[A-Z][a-z]+\s+[a-z]/.test(s)) {
      fail(`raw user-facing literal "${s}" in ${f}`);
    }
  }
}
console.log("[2] raw literal scan complete");

// ---- 3. Placeholder match (keys referenced via t("key") have all params) ----
// Require a non-identifier char before t( so createElement/querySelector/
// getElementById("div") etc. are NOT matched.
const tCallRe = /(?:^|[^A-Za-z0-9_])t\(\s*"([^"]+)"/g;
for (const f of jsFiles) {
  const src = readFileSync(join(DECODER, f), "utf8");
  let m: RegExpExecArray | null;
  while ((m = tCallRe.exec(src))) {
    const key = m[1];
    if (!enKeys.has(key) && !zhKeys.has(key)) {
      fail(`t("${key}") referenced in ${f} but missing from locale tables`);
    }
  }
}
console.log("[3] t() key reference scan complete");

// ---- 4. EMBEDDED_EN parity with locales/en.json ----
// i18n.ts ships an embedded copy of the EN table so the first paint renders
// synchronously before the locale fetch lands. It must NEVER drift from
// locales/en.json (they drifted before — the culture pass updated en.json
// but not EMBEDDED_EN, so the fallback showed stale copy). Same keys, same
// values, or this gate fails.
const i18nSrc = readFileSync(join(DECODER, "i18n.ts"), "utf8");
const embMatch = i18nSrc.match(/const EMBEDDED_EN[^=]*= \{[\s\S]*?\n\};/);
if (!embMatch) {
  fail("could not locate EMBEDDED_EN block in i18n.ts");
} else {
  let embedded: Record<string, string> | undefined;
  try {
    // The block is an object literal of JSON.stringify'd keys/values
    // (regenerated by scripts/sync-embedded.ts), so it parses as JSON.
    const literal = embMatch[0].slice(embMatch[0].indexOf("{")).replace(/;$/, "");
    embedded = JSON.parse(literal) as Record<string, string>;
  } catch (e) {
    fail("could not parse EMBEDDED_EN: " + (e instanceof Error ? e.message : String(e)));
  }
  if (embedded) {
    const embKeys = Object.keys(embedded);
    const embOnly = embKeys.filter((k) => !(k in en));
    const enOnly = Object.keys(en).filter((k) => !(k in embedded));
    for (const k of embOnly) fail(`EMBEDDED_EN key "${k}" missing from en.json`);
    for (const k of enOnly) fail(`en.json key "${k}" missing from EMBEDDED_EN`);
    for (const k of embKeys) {
      if (embedded[k] !== en[k]) {
        fail(`EMBEDDED_EN value differs from en.json for "${k}" (fallback would show stale copy)`);
      }
    }
  }
}
console.log("[4] EMBEDDED_EN parity check complete");

// ---- 5. data-i18n-content keys exist in both locales ----
// Every meta[name=description] wired with data-i18n-content must resolve to
// a real key in en.json AND zh.json (a missing key silently falls back to
// the raw key in the content attribute — broken SEO copy).
const HTML_DIRS = [
  ROOT,
  join(ROOT, "ithmb-decoder"),
  join(ROOT, "guide"),
  join(ROOT, "enterprise"),
];
const htmlFiles: string[] = [];
for (const d of HTML_DIRS) {
  try {
    for (const f of readdirSync(d)) if (f.endsWith(".html")) htmlFiles.push(join(d, f));
  } catch {
    // dir may not exist; skip
  }
}
for (const f of htmlFiles) {
  const html = readFileSync(f, "utf8");
  const re = /data-i18n-content="([^"]+)"/g;
  let m: RegExpExecArray | null;
  while ((m = re.exec(html))) {
    const key = m[1];
    if (!(key in en)) fail(`data-i18n-content "${key}" in ${f} missing from en.json`);
    if (!(key in zh)) fail(`data-i18n-content "${key}" in ${f} missing from zh.json`);
  }
}
console.log("[5] data-i18n-content key check complete");

if (failures) {
  console.error(`\n${failures} i18n integrity failure(s).`);
  process.exit(1);
}
console.log("\ni18n integrity OK.");
